---
version: '3.8'

networks:
    external_network:
        external: true
        name: ${DEFAULT_DOCKER_NETWORK}

volumes:
    mysql_data:

services:

    database:
        image: mysql:8.0
        hostname: mysql
        container_name: ${CONTAINER_NAME_PREFIX}_database
        ports:
            - 3306
        volumes:
            - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro
            - mysql_data:/var/lib/mysql
        env_file:
            - .env.container
        networks:
            external_network:
        # Graceful shutdown
        stop_grace_period: 30s
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "5"
                mode: "non-blocking"
                tag: "logging-mysql"
        healthcheck:
            test: export MYSQL_PWD="$$MYSQL_PASSWORD"; output=$$(mysqladmin ping --host=127.0.0.1 --port=3306 --user=$$MYSQL_USER 2>&1); echo $$output | grep 'mysqld is alive' || { echo $$output; exit 1; }
            start_period: 10s
            interval: 30s
            timeout: 5s
            retries: 3
